lti_tool_provider.settings:
  type: config_object
  label: LTI Tool Provider settings
  mapping:
    mapped_roles:
      type: mapping
      label: Configure mapped roles
      mapping:
        lti_role:
          type: string
          label: LTI Role
        user_role:
          type: string
          label: User Role
